### ISSUE TITLE
ETL Roadmap (continued)

### ISSUE THREAD

**Issue by riongull** [dashtesting/trello-github-etl#34]
Now that the major initial migration tasks are done (#6) we can start fresh, fix bugs, and add more features.  

The updated roadmap is the following:

### Bug fixes:

- [x] #27 
- [x] Some task level issues don't have a reference to the parent (this actually seems to be related to duplicated issues, though not all duplicated issues have this bug).
* examples:
 * https://github.com/dashtesting/migration-test-2022-01-19/issues/416
 * https://github.com/dashtesting/migration-test-2022-01-19/issues/1299
- [x] Duplicate Card level issues, one version does not have any owner (and other incomplete data), other version has owner (and complete data)
* examples *version without owner* | *version with owner*:
  * [Goal/Challenge Platform](https://github.com/dashtesting/migration-test-2022-01-19/issues/109) |  [Goal/Challenge Platform](https://github.com/dashtesting/migration-test-2022-01-19/issues/780)
  * [Masternode Multi-Party Payouts](https://github.com/dashtesting/migration-test-2022-01-19/issues/93) | [Masternode Multi-Party Payouts](https://github.com/dashtesting/migration-test-2022-01-19/issues/730)

### New features:

- [x] Create repo via API
- [x] (N/A) Create project (beta) board via API
- [x] (N/A) Create project custom fields via API
- [x] Gather columns by name (or pattern), not ID
- [x] Test populating non-string and non-custom columns:
  - [x] Status
  - [x] (N/A) Labels
  - [x] YesNo
- [x] Test again with new, non-id system
- [x] Can we put an issue on the project board twice? **NO**
- [x] Update documentation and examples / cleanup
- [x] #22
- [x] New column for "card title". Issues that are Trello card level will have the same data in both the issue title and "card title". For task level issues, this column should contain the card title. (bonus points if it links to the card level issue.)
- [x] Refine issue ownership: If the assignee is also the owner, the fallback owner should be the owner for the particular issue.

### Resources

- target [repo](https://github.com/dashtesting/migration1) for migration data
- rough [specification](https://docs.google.com/spreadsheets/d/16tC6h4iaw_Fdn_FiLxfAiNOEqRpe5azyqoTmJ7FnZiY/edit#gid=1220526302)
- [bounty](https://trello.com/c/m8w82CvE/184-incubator-on-github) on Trello

**Comment by riongull** [comment]
@spectaprod, please add production tasks here.  
- Check if you can edit the comment above (I doubt it).  
- If not, leave a comment below with tasks and I'll add them above.

**Comment by spectaprod** [comment]
I can edit infact!

**Comment by riongull** [comment]
Ah, right, because I added you to the ETL team, which has "maintain" access.

**Comment by riongull** [comment]
@coolaj86, I moved some of the checkboxes you made/had on https://github.com/dashtesting/trello-github-etl/issues/27 here instead, since they were not "Various minor bugs".  FYI, pretty sure you are able to edit my comments (e.g. to add tasks on this roadmap), so you can do that in the future.
